.Dd September 10, 2025
.Dt PLAKAR-SYNC 1
.Os
.Sh NAME
.Nm plakar-sync
.Nd Synchronize snapshots between Plakar repositories
.Sh SYNOPSIS
.Nm plakar sync
.Op Fl packfiles Ar path
.Op Ar snapshotID
.Cm to | from | with
.Ar repository
.Sh DESCRIPTION
The
.Nm plakar sync
command synchronize snapshots between two Plakar repositories.
If a specific snapshot ID is provided, only snapshots with matching
IDs will be synchronized.
.Pp
.Nm plakar sync
supports the location flags documented in
.Xr plakar-query 7
to precisely select snapshots.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl packfiles Ar path
Path where to put the temporary packfiles instead of building them in memory.
If the special value
.Sq memory
is specified then the packfiles are build in memory (the default value)
.El
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Cm to | from | with
Specifies the direction of synchronization:
.Bl -tag -width Ds
.It Cm to
Synchronize snapshots from the local repository to the specified peer
repository.
.It Cm from
Synchronize snapshots from the specified peer repository to the local
repository.
.It Cm with
Synchronize snapshots in both directions, ensuring both repositories
are fully synchronized.
.El
.It Ar repository
Path to the peer repository to synchronize with.
.El
.Sh EXAMPLES
Synchronize the snapshot
.Sq abcd
with a peer repository:
.Bd -literal -offset indent
$ plakar sync abcd to @peer
.Ed
.Pp
Bi-directional synchronization with peer repository of recent snapshots:
.Bd -literal -offset indent
$ plakar sync -since 7d with @peer
.Ed
.Pp
Synchronize all snapshots of @peer to @repo:
.Bd -literal -offset indent
$ plakar at @repo sync from @peer
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
General failure occurred, such as an invalid repository path, snapshot
ID mismatch, or network error.
.El
.Sh SEE ALSO
.Xr plakar 1 ,
.Xr plakar-query 7
