.Dd July 3, 2025
.Dt PLAKAR-AGENT 1
.Os
.Sh NAME
.Nm plakar-agent
.Nd Run the Plakar agent
.Sh SYNOPSIS
.Nm plakar agent
.Oo
.Cm start
.Op Fl foreground
.Op Fl log Ar logfile
.Op Fl teardown Ar delay
.Oc
.Nm plakar agent
.Cm stop
.Sh DESCRIPTION
The
.Nm plakar agent start
command, which is the default, starts the Plakar agent which will
execute subsequent
.Xr plakar 1
commands on their behalfs for faster processing.
.Pp
.Nm plakar agent
is executed automatically by most
.Xr plakar 1
commands and terminates by itself when idle for too long, so usually
there's no need to manually start it.
.Pp
The options for
.Nm plakar agent
.Cm start
are as follows:
.Bl -tag -width Ds
.It Fl foreground
Do not daemonize, run in the foreground and log to standard error.
.It Fl log Ar logfile
Write log output to the given
.Ar logfile
which is created if it does not exist.
The default is to log to syslog.
.It Fl teardown Ar delay
Specify the delay after which the idle agent terminate.
The
.Ar delay
parameter must be given as a sequence of decimal value,
each followed by a time unit
.Pq e.g. Dq 1m30s .
Defaults to 5 seconds.
.El
.Pp
.Nm plakar agent
.Cm stop
forces the currently running agent to stop.
This is useful when upgrading from an older
.Xr plakar 1
version were the agent was always running.
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as invalid parameters, inability to create the
repository, or configuration issues.
.El
.Sh SEE ALSO
.Xr plakar 1
